### PR TITLE
360/add send button to chatroom

### LINKED ISSUE #357: Fix user controller endpoints
[`/api/v1/users/me`](http://localhost:3000/api#/users/UserController_getCurrentUser)
[`/api/v1/users/{userName}`](http://localhost:3000/api#/users/UserController_getUserByUserName)

These two endpoints may conflict if a user has `me` as their username.

How to reproduce:

Create an user with `me` username
Logout and login with a different user
Go to http://localhost:3000/user/me
It displays the authenticated user profile instead of the `me` user profile.

### LINKED ISSUE #360: ⚛️ Add a send button to the mobile version of the chatroom

### PR DESCRIPTION
**Pull request by fizcamposancos**
close #360 
close #357

### CODE REVIEW

File: webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx [hunk 1]
```diff
@@ -36,6 +47,11 @@ const ChatroomMessageInput = ({ to }: ChatroomMessageInputProps) => {
           onInput={handleOnInput}
           onKeyDown={onEnterPress}
         />
+        <Button
```
Comment (gbudau) [inline webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx:50]: praise: Thanks for adding this button. It works perfectly.

File: webapp/src/pages/RegisterPage/RegisterPage.tsx [hunk 2]
```diff
@@ -52,6 +52,8 @@ export default function RegisterPage() {
 
     if (formValues.username === '') {
       errMessage = 'Username can not be empty';
+    } else if (formValues.username === 'me') {
+      errMessage = 'Invalid username';
```
Comment (gbudau) [inline webapp/src/pages/RegisterPage/RegisterPage.tsx:56]: suggestion: What do you think about changing the endpoints routes depending if we fetch info about the authenticated user or other users? (please regenerate the webapp generated code to test this)

Something like this:

<details>

```diff
diff --git a/transcendence-app/src/user/user.controller.ts b/transcendence-app/src/user/user.controller.ts
index aa7dfe0..81ee78e 100644
--- a/transcendence-app/src/user/user.controller.ts
+++ b/transcendence-app/src/user/user.controller.ts
@@ -68,14 +68,14 @@ export const AvatarFileInterceptor = LocalFileInterceptor({
   },
 });
 
-@Controller('users')
+@Controller()
 @UseGuards(AuthenticatedGuard)
 @ApiTags('users')
 @ApiForbiddenResponse({ description: 'Forbidden' })
 export class UserController {
   constructor(private userService: UserService) {}
 
-  @Patch()
+  @Patch('user')
   @ApiOkResponse({ description: 'Update the authenticated user', type: User })
   @ApiBadRequestResponse({ description: 'Bad Request' })
   @ApiUnprocessableEntityResponse({ description: 'Unprocessable Entity' })
@@ -93,13 +93,13 @@ export class UserController {
     return updatedUser;
   }
 
-  @Get('me')
+  @Get('user')
   @ApiOkResponse({ description: 'Get the authenticated user', type: User })
   getCurrentUser(@GetUser() user: User) {
     return user;
   }
 
-  @Get()
+  @Get('users')
   @ApiOkResponse({
     description: `Lists all users (max ${MAX_ENTRIES_PER_PAGE})`,
     type: [User],
@@ -116,7 +116,7 @@ export class UserController {
     return users;
   }
 
-  @Get(':userName')
+  @Get('users/:userName')
   @ApiOkResponse({ description: 'Get a user', type: UserResponseDto })
   @ApiNotFoundResponse({ description: 'Not Found' })
   @ApiBadRequestResponse({ description: 'Bad Request' })
@@ -134,7 +134,7 @@ export class UserController {
     return user;
   }
 
-  @Put('avatar')
+  @Put('user/avatar')
   @ApiConsumes('multipart/form-data')
   @ApiFile('file')
   @ApiProduces('image/jpeg')
@@ -168,7 +168,7 @@ export class UserController {
     return avatar;
   }
 
-  @Get('block/list')
+  @Get('user/block')
   @ApiOkResponse({
     description: 'List users blocked by the authenticated user',
     type: [User],
@@ -182,7 +182,7 @@ export class UserController {
     return blockedUsers;
   }
 
-  @Post('block/:userId')
+  @Post('user/block/:userId')
   @HttpCode(HttpStatus.NO_CONTENT)
   @ApiNoContentResponse({ description: 'Block a user' })
   @ApiBadRequestResponse({ description: 'Bad Request' })
@@ -194,7 +194,7 @@ export class UserController {
     return this.userService.addBlock(user.id, blockedUserId);
   }
 
-  @Delete('block/:userId')
+  @Delete('user/block/:userId')
   @HttpCode(HttpStatus.NO_CONTENT)
   @ApiNoContentResponse({
     description: 'Unblock a user',
diff --git a/webapp/src/pages/RegisterPage/RegisterPage.tsx b/webapp/src/pages/RegisterPage/RegisterPage.tsx
index 51a4f5f..d4c79cf 100644
--- a/webapp/src/pages/RegisterPage/RegisterPage.tsx
+++ b/webapp/src/pages/RegisterPage/RegisterPage.tsx
@@ -52,8 +52,6 @@ export default function RegisterPage() {
 
     if (formValues.username === '') {
       errMessage = 'Username can not be empty';
-    } else if (formValues.username === 'me') {
-      errMessage = 'Invalid username';
     } else if (formValues.email === '') {
       errMessage = 'Email can not be empty';
     } else if (formValues.fullName === '') {
diff --git a/webapp/src/shared/components/Button/Button.css b/webapp/src/shared/components/Button/Button.css
index 773855c..bf0da2a 100644
--- a/webapp/src/shared/components/Button/Button.css
+++ b/webapp/src/shared/components/Button/Button.css
@@ -6,6 +6,7 @@
   align-items: center;
   cursor: pointer;
   display: flex;
+  gap: 1rem;
   flex-direction: row;
   justify-content: center;
 }

```

</details>

File: webapp/src/shared/components/Button/Button.css [hunk 3]
```diff
@@ -42,6 +42,4 @@
 
 .button-icon {
   display: flex;
-  position: absolute;
-  left: 1rem;
```
Comment (gbudau) [inline webapp/src/shared/components/Button/Button.css:46]: praise: Nice detail. Now the icon of the small button is centered :+1:

**Review by gbudau — APPROVED** [review]
Thank you for this feature! LGTM :rocket:

**Comment by Damrod** [comment]
What about we do this:

```
diff --git a/webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx b/webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx
index 92c6a6c..bd8b547 100644
--- a/webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx
+++ b/webapp/src/pages/ChatroomPage/components/ChatroomMessageInput/ChatroomMessageInput.tsx
@@ -1,6 +1,7 @@
 import React, { useState } from 'react';
 import {
   Button,
+  ButtonSize,
   ButtonVariant,
   IconVariant,
 } from '../../../../shared/components';
@@ -16,7 +17,8 @@ const ChatroomMessageInput = ({ to }: ChatroomMessageInputProps) => {
 
   const handleButtonSend = (e: React.MouseEvent): void => {
     e.preventDefault();
-    socket.emit('chatroomMessage', { chatroomId: to, content: value });
+    value !== '' &&
+      socket.emit('chatroomMessage', { chatroomId: to, content: value });
     setValue('');
   };
 
@@ -51,6 +53,7 @@ const ChatroomMessageInput = ({ to }: ChatroomMessageInputProps) => {
           variant={ButtonVariant.SUBMIT}
           iconVariant={IconVariant.SEND}
           onClick={handleButtonSend}
+          buttonSize={ButtonSize.SMALL}
         />
       </div>
     </form>
diff --git a/webapp/src/shared/components/Button/Button.tsx b/webapp/src/shared/components/Button/Button.tsx
index 84d5b2e..16641b7 100644
--- a/webapp/src/shared/components/Button/Button.tsx
+++ b/webapp/src/shared/components/Button/Button.tsx
@@ -53,7 +53,17 @@ export default function Button({
       form={form}
     >
       {iconVariant && (
-        <div className="button-icon">
+        <div
+          className="button-icon"
+          style={
+            (buttonSize === ButtonSize.LARGE &&
+              children && {
+                position: 'absolute',
+                left: '1rem',
+              }) ||
+            undefined
+          }
+        >
           {<Icon variant={iconVariant} size={IconSize.SMALL} />}
         </div>
       )}
```

File: webapp/src/shared/components/Button/Button.css (hunk 3 above)
Comment (Damrod) [reply webapp/src/shared/components/Button/Button.css:46]: I'd still prefer the large button to keep the style it used to have, otherwise icon and button label almost overlap
Below the necessary change to achieve this.

Comment (fizcamposancos) [reply webapp/src/shared/components/Button/Button.css]: Done!

File: webapp/src/pages/RegisterPage/RegisterPage.tsx (hunk 2 above)
Comment (fizcamposancos) [reply webapp/src/pages/RegisterPage/RegisterPage.tsx]: Done

**Review by Damrod — APPROVED** [review]
LGTM! Thx

**Review by vdedios — APPROVED** [review]
Very nice 💯
