### PR TITLE
Fix OpenAPI Generator

### LINKED ISSUE #173: Fix openapi-generator script
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
        -attribute components.schemas.User.default is not of type `object`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

### PR DESCRIPTION
**Pull request by gbudau**
close #173

### CODE REVIEW

File: transcendence-app/src/main.ts [hunk 1]
```diff
@@ -29,7 +30,8 @@ async function bootstrap() {
     .setVersion('1.0')
     .build();
   const document = SwaggerModule.createDocument(app, options);
-  writeFileSync('./swagger-spec.json', JSON.stringify(document));
+  const yamlString: string = yaml.stringify(document, {});
+  writeFileSync('./swagger-spec.yaml', yamlString);
```
Comment (gbudau) [inline transcendence-app/src/main.ts:34]: I've changed this to YAML format because it's more readable.

File: transcendence-app/src/user/user.domain.ts [hunk 2]
```diff
@@ -8,8 +9,8 @@ export class User {
   @Exclude()
   password!: string | null;
   avatarId!: string | null;
-  avatarX = 0;
-  avatarY = 0;
+  avatarX: number = 0;
+  avatarY: number = 0;
```
Comment (gbudau) [inline transcendence-app/src/user/user.domain.ts:13]: The OpenAPI generator needs these types, even if TypeScript could infer them.
I've removed them in a previous PR :sweat_smile:

**Review by vdedios — APPROVED** [review]
:+1:

**Comment by gbudau** [comment]
:rocket:
